#ifndef LEANHTTP_CURL_OPTIONS_H
#define LEANHTTP_CURL_OPTIONS_H

#include <curl/curl.h>

#define LEANHTTP_ASSERT_OPT(name, value) _Static_assert((unsigned long)(name) == (value), #name " changed")
LEANHTTP_ASSERT_OPT(CURLOPT_URL, 10002);
LEANHTTP_ASSERT_OPT(CURLOPT_PROXY, 10004);
LEANHTTP_ASSERT_OPT(CURLOPT_USERPWD, 10005);
LEANHTTP_ASSERT_OPT(CURLOPT_POSTFIELDS, 10015);
LEANHTTP_ASSERT_OPT(CURLOPT_USERAGENT, 10018);
LEANHTTP_ASSERT_OPT(CURLOPT_SSLCERT, 10025);
LEANHTTP_ASSERT_OPT(CURLOPT_CUSTOMREQUEST, 10036);
LEANHTTP_ASSERT_OPT(CURLOPT_NOBODY, 44);
LEANHTTP_ASSERT_OPT(CURLOPT_FOLLOWLOCATION, 52);
LEANHTTP_ASSERT_OPT(CURLOPT_SSL_VERIFYPEER, 64);
LEANHTTP_ASSERT_OPT(CURLOPT_CAINFO, 10065);
LEANHTTP_ASSERT_OPT(CURLOPT_MAXREDIRS, 68);
LEANHTTP_ASSERT_OPT(CURLOPT_HTTPGET, 80);
LEANHTTP_ASSERT_OPT(CURLOPT_SSL_VERIFYHOST, 81);
LEANHTTP_ASSERT_OPT(CURLOPT_HTTP_VERSION, 84);
LEANHTTP_ASSERT_OPT(CURLOPT_SSLKEY, 10087);
LEANHTTP_ASSERT_OPT(CURLOPT_ACCEPT_ENCODING, 10102);
LEANHTTP_ASSERT_OPT(CURLOPT_HTTPAUTH, 107);
LEANHTTP_ASSERT_OPT(CURLOPT_MAXFILESIZE_LARGE, 30117);
LEANHTTP_ASSERT_OPT(CURLOPT_TIMEOUT_MS, 155);
LEANHTTP_ASSERT_OPT(CURLOPT_CONNECTTIMEOUT_MS, 156);
LEANHTTP_ASSERT_OPT(CURLOPT_NOPROXY, 10177);
LEANHTTP_ASSERT_OPT(CURLOPT_TCP_KEEPALIVE, 213);
LEANHTTP_ASSERT_OPT(CURLOPT_XOAUTH2_BEARER, 10220);
#undef LEANHTTP_ASSERT_OPT

#endif
