#ifndef LEANHTTP_CURL_OPTIONS_H
#define LEANHTTP_CURL_OPTIONS_H

#include <curl/curl.h>
#include <curl/websockets.h>

#define LEANHTTP_ASSERT_OPT(name, value) _Static_assert((unsigned long)(name) == (value), #name " changed")
LEANHTTP_ASSERT_OPT(CURLOPT_URL, 10002);
LEANHTTP_ASSERT_OPT(CURLOPT_PROXY, 10004);
LEANHTTP_ASSERT_OPT(CURLOPT_USERPWD, 10005);
LEANHTTP_ASSERT_OPT(CURLOPT_POSTFIELDS, 10015);
LEANHTTP_ASSERT_OPT(CURLOPT_USERAGENT, 10018);
LEANHTTP_ASSERT_OPT(CURLOPT_SSLCERT, 10025);
LEANHTTP_ASSERT_OPT(CURLOPT_CUSTOMREQUEST, 10036);
LEANHTTP_ASSERT_OPT(CURLOPT_NOBODY, 44);
LEANHTTP_ASSERT_OPT(CURLOPT_FOLLOWLOCATION, 52);
LEANHTTP_ASSERT_OPT(CURLOPT_SSL_VERIFYPEER, 64);
LEANHTTP_ASSERT_OPT(CURLOPT_CAINFO, 10065);
LEANHTTP_ASSERT_OPT(CURLOPT_MAXREDIRS, 68);
LEANHTTP_ASSERT_OPT(CURLOPT_HTTPGET, 80);
LEANHTTP_ASSERT_OPT(CURLOPT_CONNECT_ONLY, 141);
LEANHTTP_ASSERT_OPT(CURLOPT_SSL_VERIFYHOST, 81);
LEANHTTP_ASSERT_OPT(CURLOPT_HTTP_VERSION, 84);
LEANHTTP_ASSERT_OPT(CURLOPT_SSLKEY, 10087);
LEANHTTP_ASSERT_OPT(CURLOPT_ACCEPT_ENCODING, 10102);
LEANHTTP_ASSERT_OPT(CURLOPT_HTTPAUTH, 107);
LEANHTTP_ASSERT_OPT(CURLOPT_MAXFILESIZE_LARGE, 30117);
LEANHTTP_ASSERT_OPT(CURLOPT_TIMEOUT_MS, 155);
LEANHTTP_ASSERT_OPT(CURLOPT_CONNECTTIMEOUT_MS, 156);
LEANHTTP_ASSERT_OPT(CURLOPT_NOPROXY, 10177);
LEANHTTP_ASSERT_OPT(CURLOPT_TCP_KEEPALIVE, 213);
LEANHTTP_ASSERT_OPT(CURLOPT_PATH_AS_IS, 234);
LEANHTTP_ASSERT_OPT(CURLOPT_XOAUTH2_BEARER, 10220);
LEANHTTP_ASSERT_OPT(CURLINFO_ACTIVESOCKET, 5242924);
#undef LEANHTTP_ASSERT_OPT

/* WebSocket frame flags, mirrored by LeanHttp.WebSocket. */
#define LEANHTTP_ASSERT_WS(name, value) _Static_assert((unsigned long)(name) == (value), #name " changed")
LEANHTTP_ASSERT_WS(CURLWS_TEXT, 1);
LEANHTTP_ASSERT_WS(CURLWS_BINARY, 2);
LEANHTTP_ASSERT_WS(CURLWS_CONT, 4);
LEANHTTP_ASSERT_WS(CURLWS_CLOSE, 8);
LEANHTTP_ASSERT_WS(CURLWS_PING, 16);
LEANHTTP_ASSERT_WS(CURLWS_OFFSET, 32);
LEANHTTP_ASSERT_WS(CURLWS_PONG, 64);
#undef LEANHTTP_ASSERT_WS

#endif
